name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt -t lambdas/common

      - name: Package Lambda functions
        run: |
          cd lambdas/authorizer
          zip -r ../../authorizer.zip *  # Zips only the contents of the folder without including 'lambdas'
          cd ../wrapped
          zip -r ../../wrapped.zip *  # Zips only the contents of the folder without including 'lambdas'
          cd ../..
          zip -r xomify-shared-packages.zip lambdas/common

      - name: Deploy Lambda Layer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          LAYER_OUTPUT=$(aws lambda publish-layer-version \
            --layer-name xomify-shared-packages \
            --zip-file fileb://xomify-shared-packages.zip \
            --compatible-runtimes python3.10 \
            --region $AWS_REGION \
            --output json)

          echo "LAYER_ARN=$(echo $LAYER_OUTPUT | jq -r .LayerVersionArn)" >> $GITHUB_ENV
          echo "Layer ARN: $LAYER_ARN"

      - name: Deploy Lambda Function Code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          aws lambda update-function-code \
            --function-name xomify-authorizer \
            --zip-file fileb://authorizer.zip
          aws lambda update-function-code \
            --function-name xomify-wrapped \
            --zip-file fileb://wrapped.zip

      - name: Deploy Lambda Configurations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          LAYER_ARN: ${{ env.LAYER_ARN }}
        run: |
          aws lambda update-function-configuration \
            --function-name xomify-authorizer \
            --layers $LAYER_ARN \
            --region $AWS_REGION
          aws lambda update-function-configuration \
            --function-name xomify-wrapped \
            --layers $LAYER_ARN \
            --region $AWS_REGION
